---
version: '3.7'
services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        cap_add:
            - SYS_NICE
        restart: always
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
            - '3306:3306'
        volumes:
            - mysql:/var/lib/mysql
volumes:
    mysql:
        driver: local
